FROM registry.access.redhat.com/ubi8/dotnet-70:7.0-18
LABEL "io.openshift.s2i.build.image"="registry.access.redhat.com/ubi8/dotnet-70:7.0-18" \
      "io.openshift.s2i.build.commit.author"="Ryan Nix <rnix@redhat.com>" \
      "io.openshift.s2i.build.commit.date"="Tue Jul 25 11:29:21 2023 -0500" \
      "io.openshift.s2i.build.commit.id"="2af7e44a3a0d0f2728adb75d42775fd70f867ac8" \
      "io.openshift.s2i.build.commit.ref"="main" \
      "io.openshift.s2i.build.commit.message"="Removing Containerfile" \
      "io.openshift.s2i.build.source-location"="https://github.com/ryannix123/dotnet-example.git"

USER root
# Copying in source code
COPY upload/src /tmp/src
# Change file ownership to the assemble user. Builder image must support chown command.
RUN chown -R 1001:0 /tmp/src
USER 1001
# Assemble script sourced from builder image based on user input or image metadata.
# If this file does not exist in the image, the build will fail.
RUN /usr/libexec/s2i/assemble
# Run script sourced from builder image based on user input or image metadata.
# If this file does not exist in the image, the build will fail.
CMD /usr/libexec/s2i/run
